### PR TITLE
Centralize tests

### PR DESCRIPTION
**Pull request by praiskup**

### CODE REVIEW

**Comment by praiskup** [comment]
@omron93, looks like there's some bug in the script;  the CI reports "no space left on device".  Can you debug?

**Comment by praiskup** [comment]
[test] let's try again, Jenkins :), before we hack you ...

**Comment by praiskup** [comment]
[test]

**Comment by pkubatrh** [comment]
It seems like the `Required-by` commit message does not start the tests for mongodb (I can only see runs for postgresql and python in the CI). Possibly related:

```
10:05:57 fatal: unrecognized argument: --no-patch
10:05:57 fatal: unrecognized argument: --no-patch
10:05:57 fatal: unrecognized argument: --no-patch
10:05:57 fatal: unrecognized argument: --no-patch
10:05:57 fatal: unrecognized argument: --no-patch
10:05:57 fatal: unrecognized argument: --no-patch
10:05:57 fatal: unrecognized argument: --no-patch
```

**Comment by hhorak** [comment]
@praiskup It looks like tests are green, anything else is missing? It looks very nice to me..

**Comment by pkubatrh** [comment]
@hhorak @praiskup I do not think the issue with `--no-patch` has been resolved yet. Given that (afaik) we want to test this PR against mongodb-container#258 we should first make sure the tests are run as expected.

**Comment by praiskup** [comment]
Right, I tried to solve this via #28.

**Comment by hhorak** [comment]
Weird, I'd expect centos7 and rhel7 to have the same version of git..

**Comment by praiskup** [comment]
Sorry, that's wrongly named ticket;  the issue is on both centos7/rhel7.  By RHEL7 I meant any el7 "fork".

**Comment by praiskup** [comment]
Ok, I squashed Tomas's commits into one; and fixed the testsuite (commit nr. 1).  The CI seems to pass, so should we merge and continue with the development later? @omron93, @pkubatrh, @hhorak ?

**Comment by praiskup** [comment]
Ping, can we merge?

**Comment by omron93** [comment]
+1 for merging. This look really good. Thanks.

**Comment by pkubatrh** [comment]
lgtm, tests are passing against mongodb now, so merging. Thanks!

**Pull request merged**
