### PR TITLE
Support branch definition in URL for git clone command

### PR DESCRIPTION
**Pull request by frenzymadness**
In Python container, we need to test two different branches of [Django example project](https://github.com/sclorg/django-ex) because the old LTS version is EOL and the new one does not work on RHEL/Centos 7.

Inspired by [pip](https://pip.pypa.io/en/stable/reference/pip_install/#git), I've implemented a way to get a branch name from git repo URL for `ct_test_app_dockerfile` function. Basically, whatever you put after a `@` in a git repository URL is considered as a name of a branch and used in `git clone --branch <name>`.

I'm not sure on how many places and in how many ways we are doing `git clone` but, if accepted, we can implement the same behavior for all `git clone` and `s2i build` commands.

### CODE REVIEW

**Comment by frenzymadness** [comment]
[test]

**Comment by frenzymadness** [comment]
`toomanyrequests: You have reached your pull rate limit. You may increase the limit by authenticating and upgrading: https://www.docker.com/increase-rate-limit` :disappointed:

**Comment by frenzymadness** [comment]
[test]

**Comment by pkubatrh** [comment]
[test]

**Review by phracek — APPROVED** [review]
LGTM. I have tested locally and the code is fine. Thanks for the PR!

**Comment by phracek** [comment]
I will test this PR locally whether tests are passing.

**Comment by frenzymadness** [comment]
Thank you!

**Pull request merged**
