### PR TITLE
Always set 'set -e' explicitly

### PR DESCRIPTION
**Pull request by praiskup**
Using '-e' in shebang is not secure since executing the script
like 'bash /the-script' isn't taking the additional options into
account.

Fixes regression caused by 44fb885e2e6b03

### CODE REVIEW

**Comment by praiskup** [comment]
[test]

**Comment by praiskup** [comment]
Meh, sorry about this.  We should fix this rather sooner than later till not many
images depend on this.  Basically failed test case could be overlooked.

**Comment by praiskup** [comment]
[test]

**Comment by praiskup** [comment]
[test]

**Comment by praiskup** [comment]
Merged early without review, to not risk that others will depend on broken
commons.

**Comment by pkubatrh** [comment]
Makes sense, thanks!

**Pull request merged**
