### PR TITLE
Calculate available cores from cpu cgroups controller

### PR DESCRIPTION
**Pull request by yrro**
Fixes: https://github.com/sclorg/s2i-base-container/issues/180

### CODE REVIEW

**Comment by frenzymadness** [comment]
I guess from the comments in the original PR that this is ready to be merged. What do you say, @phracek ?

**Comment by phracek** [comment]
[test]

**Comment by phracek** [comment]
Sanity tests are failing for this reason:

```bash
pre-commit run --all
Warning:  Unexpected key(s) present on https://github.com/ambv/black: language_version
[INFO] Initializing environment for https://github.com/ambv/black.
[INFO] Initializing environment for https://github.com/pre-commit/pre-commit-hooks.
[INFO] Initializing environment for https://github.com/pre-commit/mirrors-mypy.
[INFO] Installing environment for https://github.com/ambv/black.
[INFO] Once installed this environment will be reused.
[INFO] This may take a few minutes...
[INFO] Installing environment for https://github.com/pre-commit/pre-commit-hooks.
[INFO] Once installed this environment will be reused.
[INFO] This may take a few minutes...
[INFO] Installing environment for https://github.com/pre-commit/mirrors-mypy.
[INFO] Once installed this environment will be reused.
[INFO] This may take a few minutes...
black....................................................................Failed
- hook id: black
- exit code: 1
Traceback (most recent call last):
  File "/home/runner/.cache/pre-commit/repoospg5i6_/py_env-python3/bin/black", line 8, in <module>
    sys.exit(patched_main())
  File "/home/runner/.cache/pre-commit/repoospg5i6_/py_env-python3/lib/python3.8/site-packages/black.py", line 3753, in patched_main
    patch_click()
  File "/home/runner/.cache/pre-commit/repoospg5i6_/py_env-python3/lib/python3.8/site-packages/black.py", line 3742, in patch_click
    from click import _unicodefun  # type: ignore
ImportError: cannot import name '_unicodefun' from 'click' (/home/runner/.cache/pre-commit/repoospg5i6_/py_env-python3/lib/python3.8/site-packages/click/__init__.py)

```
Can you please fix it?
Just call these three commands:
```
$ pip3 install pre-commit
$ pre-commit install
$ pre-commit run --all
```

**Comment by frenzymadness** [comment]
The problem seems to be in pre-commit, let me take a look.

**Comment by frenzymadness** [comment]
@yrro could you please update the pre-commit or should I handle it?

**Comment by phracek** [comment]
> 

I prefer to use the latest and remove the dependency.

**Comment by phracek** [comment]
> The problem is described [here](https://github.com/psf/black/issues/2964). What we can do to fix it is to simply upgrade black in pre-commit config file to the latest version 22.6.0 and remove the line with additional dependencies, because:
> 
>     * black depends on click, there is no need for having it as an additional dependency, and
> 
>     * the combination of black 22.1.0 and click 8.0.4 we currently have in the config file should work but it does not and newer click is installed so it seems that the additional dependencies don't work as intended.

I prefer to use the latest and remove the dependency.

**Comment by phracek** [comment]
RHEL-9 tests are failing because of the subscription manager. It is fixed by https://github.com/sclorg/container-common-scripts/pull/271

**Comment by frenzymadness** [comment]
[test]

**Comment by phracek** [comment]
PR https://github.com/sclorg/container-common-scripts/pull/271 is merged let's trigger tests again.

[test]

**Comment by phracek** [comment]
The tests are failing because the PR has to be rebased against master.
```bash
 # FATAL: Please rebase the commit '07c0b26' to allow --ff merge into 'origin/master' branch
make: *** [test] Error 1
```

**Comment by phracek** [comment]
[test]

**Comment by phracek** [comment]
RHEL9 failures are fixed by https://github.com/sclorg/container-common-scripts/pull/272

**Comment by yrro** [comment]
Thanks, will rebase once that's merged

**Comment by yrro** [comment]
Thanks - rebased

**Comment by phracek** [comment]
Fedora test has failed on `pino` client:

```bash
14:23:37                 out:  [PASSED] for 'clients' express
14:23:37                 out:  [FAILED] for 'clients' pino
14:23:37                 out:  [PASSED] for 'clients' prom-client
14:23:37                 out:  [PASSED] for 'clients' opossum
```

**Review by phracek — APPROVED** [review]
LGTM.

**Comment by yrro** [comment]
Thanks!

**Pull request merged**
