### PR TITLE
do not source the OC library if already sourced

### PR DESCRIPTION
**Pull request by zmiklank**

### CODE REVIEW

**Comment by phracek** [comment]
@zmiklank Make sense to me to not include the source file twice. Can you please do it also for the other files?

@hhorak @pkubatrh WDYT bash experts? Does it make sense also from your point of view?

**Comment by zmiklank** [comment]
Yes, if we proceed with this proposal I will add the check also to other libs.

**Comment by zmiklank** [comment]
[test-all]

**Comment by hhorak** [comment]
lgtm

**Comment by zmiklank** [comment]
[test-all]

**Comment by zmiklank** [comment]
Fixes: https://github.com/sclorg/postgresql-container/issues/478

**Pull request merged**
