### PR TITLE
test-libs: add the ability to set ImageStream name and tag

### PR DESCRIPTION
**Pull request by pkubatrh**
Related to: https://github.com/sclorg/postgresql-container/pull/206

### CODE REVIEW

**Comment by pkubatrh** [comment]
@praiskup @omron93 ptal

**Comment by praiskup** [comment]
Could we fix the method's documentation (it takes optionally two arguments now).

**Comment by pkubatrh** [comment]
Fixed, thanks!

**Comment by praiskup** [comment]
I'm not terribly familiar with these testing concepts, but merging. Thank you.

**Pull request merged**
