### PR TITLE
Add a new funciton ct_wait_container_port

### PR DESCRIPTION
**Pull request by hhorak**
This function that can be used for starting up a container, instead of sleep calls.

Using it can hopefully help to get rid of random test failures seen at https://github.com/sclorg/httpd-container/pull/92.

### CODE REVIEW

**Comment by praiskup** [comment]
At least this isn't enough in case of PostgreSQL ... there's pretty sophisticated method of
checking whether postgresql booted fine (see the liveness/readiness check in PG container).

**Comment by hhorak** [comment]
Right, for db containers, we should probably use more specific method. This might be useful for webapps, where having port opened is usually ok. Although I'm thinking now whether it shouldn't be rather more specific functionality and instead of checking a port readiness, check output of curl call repeatedly and timeout if the daemon does not return expected string.

**Comment by praiskup** [comment]
On Monday, March 23, 2020 7:15:30 PM CET Honza Horak wrote:
> Right, for db containers, we should probably use more specific method.

Perhaps, if specified, you could use the defined readiness/liveness check
directly?

**Comment by hhorak** [comment]
> On Monday, March 23, 2020 7:15:30 PM CET Honza Horak wrote: Right, for db containers, we should probably use more specific method.
> Perhaps, if specified, you could use the defined readiness/liveness check directly?

Not sure I'm still following, do you mean like `podman exec /usr/libexec/check-container`? (https://github.com/sclorg/postgresql-container/blob/master/examples/postgresql-ephemeral-template.json#L133)

**Comment by praiskup** [comment]
On Monday, March 23, 2020 7:35:51 PM CET Honza Horak wrote:
> do you mean like `podman exec /usr/libexec/check-container`?

That's what I meant but I'm not sure it is possible.  Sorry for interrupt,
feel free to continue with this...

**Comment by pkubatrh** [comment]
I agree. Would be nice to check container readiness the same way we do it in the templates if possible.

**Comment by hhorak** [comment]
> I agree. Would be nice to check container readiness the same way we do it in the templates if possible.

Agreed, where we have templates, it's the way to go.

But we don't have such templates for s2i images like httpd (that this PR was originally inspired by) -- those need either "curl in loop" or in worse case (e.g. httpd) they use "sleep X" and see test failures when X is not enough from some reason (that is the reason why tests are failing in sclorg/httpd-container#92 now).

So, what I'm after here is that exact case -- either have a generic function that waits until a port is listening, or till that port also serves some content (in case HTTP protocol is used in such cases, which seems to be the case). It doesn't seem to be worth re-defining such function in every container test script.

**Comment by hhorak** [comment]
It looks like the waiting in loop can be achieved also with the `ct_test_response` function, at least in the case of httpd container that was my primary concern. The tests could be converted to not use sleep as seen in https://github.com/sclorg/httpd-container/pull/94. Therefore, closing this PR for now as there is probably not good enough need for this new function.

**Comment by praiskup** [comment]
It's a pity this stayed unmerged.  I didn't want to discourage you from
merging.

**Comment by hhorak** [comment]
> It's a pity this stayed unmerged. I didn't want to discourage you from merging.

No worry, I just didn't see much value in it after all, and it's always useful to save some code.. removed code, good code :)

**Comment by hhorak** [comment]
Still see no real need for this, closing.

**Pull request closed without merging**
