### PR TITLE
cgroups: return None if number of cores can not be obtained

### PR DESCRIPTION
**Pull request by zmiklank**
Fixes: https://github.com/sclorg/postgresql-container/issues/482

### CODE REVIEW

**Comment by zmiklank** [comment]
[test-all]

**Comment by zmiklank** [comment]
@pkubat could you please look at this?

Another approach could be to return at least something, if either _read_cpu_quota() or _read_cpuset_size() is successful. Wdyt?

**Comment by pkubatrh** [comment]
Since the `return` part already expects `None` in the list items, we should instead check if there are only `None` values in the list.

**Comment by zmiklank** [comment]
Oh, you are right.

**Comment by zmiklank** [comment]
Fixed.

**Comment by pkubatrh** [comment]
[test-all]

**Comment by pkubatrh** [comment]
LGTM if tests pass

**Comment by zmiklank** [comment]
This change will not appear in the test results, because they affect the s2i-core-container -> other containers would need be to be rebuilt on top of it first, in order to propagate the change.

**Pull request merged**
