### PR TITLE
Use timeout utility instead of double-sub-shell hell

### PR DESCRIPTION
**Pull request by hhorak**
It turned out that for incremental builds for Node.js, the test always waited 10m no matter that the build finished sooner.

It's not clear why it happened, but when debugging, it seemed like some weired race-condition happened that let some sleeps hang.

Anyway, it's not clear whether there is a reason to not use timeout utility that seems to serve exactly for this reason.

### CODE REVIEW

**Comment by hhorak** [comment]
@SlouchyButton Any idea why `timeout` could be a problem here?

**Comment by hhorak** [comment]
[test]

**Comment by hhorak** [comment]
[test]

**Comment by hhorak** [comment]
[test]

**Review by SlouchyButton — APPROVED** [review]
Tested on Node.js container on all supported targets and versions. All tests seem to be working.

Code is cleaner and more readable.

**Review by phracek — APPROVED** [review]
LGTM. Let's spread it into containers and we will see the updates.

**Comment by phracek** [comment]
[test]

**Comment by phracek** [comment]
[test]

**Comment by hhorak** [comment]
[test]

**Comment by phracek** [comment]
Let's get merge it and distribute to s2i-nodejs-container as first.

**Pull request merged**
