### PR TITLE
[WIP] Modify common scripts so that they work on both podman and docker

### PR DESCRIPTION
**Pull request by pkubatrh**
Expecting docker -> podman symlink/wrapper

### CODE REVIEW

**Comment by praiskup** [comment]
[test]

**Comment by pkubatrh** [comment]
[test]

**Comment by omron93** [comment]
@pkubatrh About our CI: is podman going to be available in RHEL7 ?

@pkubatrh @praiskup @hhorak and should we use it instead of docker?

**Comment by praiskup** [comment]
@omron93 wrote:
>  should we use it instead of docker?

I think we could test it as soon as it is reasonably possible, but it is not right time to switch yet (my guess is that we'll have to support both in future for some period of time)

**Comment by praiskup** [comment]
LGTM

**Comment by pkubatrh** [comment]
>should we use it instead of docker?

It would be nice to use it for Fedora versions I guess. As soon as our tests are able to work with it.

**Pull request merged**
