### PR TITLE
Use tag in case of s2i strategy

### PR DESCRIPTION
**Pull request by hhorak**
Otherwise we see an error like:

    Importing image quay.io/centos7/ruby-25-centos7 as sclorg-test-9971/ruby-25-centos7
    error: ruby-25-centos7 must be of the form <stream_name>:<tag>

### CODE REVIEW

**Comment by hhorak** [comment]
@phracek @pkubatrh @fila43 This is what I mentioned on the meeting on Wednesday, that could help the failures of OpenShift tests. Feel free to merge if you don't spot any issue.

**Review by phracek — APPROVED** [review]
LGTM. Thanks.

**Comment by phracek** [comment]
[test][test-openshift]

**Comment by phracek** [comment]
And of course. Thanks for this fix!!!

**Comment by phracek** [comment]
[test]

**Comment by hhorak** [comment]
[test]

**Comment by hhorak** [comment]
The build fails because of docker.io pull limit, reported as #188 and it might be fixed separately using #189

**Pull request merged**
