### PR TITLE
Add functions for testing example apps for s2i images

### PR DESCRIPTION
**Pull request by hhorak**
Running test for nginx-ex may be then as simple as this:
```
ct_os_test_template_app ${IMAGE_NAME} \
                        nginx.json \
                        nginx \
                        'Welcome to your static nginx application on OpenShift' \
                        8080 http 200 "-p SOURCE_REPOSITORY_REF=staging -p NGINX_VERSION=${VERSION}"
```

### CODE REVIEW

**Comment by hhorak** [comment]
@pvalena these are the functions I meant.

**Comment by pvalena** [comment]
LGTM.

**Comment by pvalena** [comment]
Feel free to merge.

**Comment by hhorak** [comment]
Cool, thanks.

**Pull request merged**
