### PR TITLE
make imageID prefix optional as podman changed output format

### PR DESCRIPTION
**Pull request by pkubatrh**
related: https://github.com/containers/libpod/issues/3191

### CODE REVIEW

**Comment by pkubatrh** [comment]
[test]

**Comment by praiskup** [comment]
+1

**Comment by pkubatrh** [comment]
rhel8 CI fails because of https://github.com/sclorg/container-common-scripts/issues/122

Considering this change mostly affects rhel8 we should wait until that issue is fixed before merging

**Comment by pkubatrh** [comment]
rebased

[test]

**Comment by pkubatrh** [comment]
Tests are green now so merging

**Pull request merged**
