### PR TITLE
Build and tag the non-minimal variant as well

### PR DESCRIPTION
**Pull request by hhorak**
Without having the non-minimal image build and tagged, the image might be missing (sometimes it's not available in the repository yet, for new versions specifically), so let's build and tag it as well.

### CODE REVIEW

**Comment by hhorak** [comment]
For example needed for https://github.com/sclorg/s2i-nodejs-container/pull/400

**Review by phracek — CHANGES_REQUESTED** [review]
Good catch. Let's try it in CI, where it works.

What about 'micro' images? LIke in https://github.com/httpd-container/2.4-micro?

Before merging this pull request we need to analyse logs at least for s2i-nodejs-container which contains 'minimal' images and 'httpd-container' logs

**Comment by phracek** [comment]
[test]

**Comment by hhorak** [comment]
[test]

**Comment by hhorak** [comment]
> Good catch. Let's try it in CI, where it works.
> 
> What about 'micro' images? LIke in https://github.com/httpd-container/2.4-micro?
> 
> Before merging this pull request we need to analyse logs at least for s2i-nodejs-container which contains 'minimal' images and 'httpd-container' logs

I think micro might be included as well, good point.

**Comment by hhorak** [comment]
[test]

**Review by phracek — APPROVED** [review]

**Pull request merged**
