### PR TITLE
Remove symlink loop causing troubles for rsync

### PR DESCRIPTION
**Pull request by frenzymadness**
Fixes: https://github.com/sclorg/container-common-scripts/issues/205

The check-failures test works well as before and it also tests that the `common_dir` in `common.mk` works as expected because this is now the only piece of code that actually uses it.

### CODE REVIEW

**Comment by frenzymadness** [comment]
@praiskup you are the one who created the symlink loop in #60 so could you please take a look at whether this solution works for you?

**Comment by frenzymadness** [comment]
[test]

**Comment by frenzymadness** [comment]
I'm not sure what is happening in the CI but the error does not seem to be related to this change.

**Comment by praiskup** [comment]
[test]

**Comment by zmiklank** [comment]
[test-all]

**Comment by zmiklank** [comment]
Hi Lumir,
sorry for late noticing. The tests I have ran now will fail, because the branch is not rebased on master (which is of course, as the PR has been opened for a long time.) Could you please rebase the branch?

**Comment by zmiklank** [comment]
@frenzymadness Or I can rebase it, if you would not mind.

**Comment by frenzymadness** [comment]
I totally forgot about this PR. It's now rebased. [test-all]

**Review by zmiklank — APPROVED** [review]
Lgtm, thanks.

**Pull request merged**
