### PR TITLE
Make some testing functions more verbose for debugging

### PR DESCRIPTION
**Pull request by frenzymadness**
These changes helped me a lot when I was debugging some failures for my latest pull requests for Python containers. What do you think about them?

### CODE REVIEW

**Comment by phracek** [comment]
Thanks for more traces.

[test]

**Comment by phracek** [comment]
@frenzymadness I have fixed Github rate limit by this PR https://github.com/sclorg/container-common-scripts/pull/196
Please rebase it. After rebase tests should pass.

**Comment by phracek** [comment]
[test]

**Comment by frenzymadness** [comment]
I'm not sure why are the tests failing.

**Comment by zmiklank** [comment]
[test-all]

**Review by zmiklank — APPROVED** [review]

**Pull request merged**
