### PR TITLE
Small compatability fix

### PR DESCRIPTION
**Pull request by jbornemann**
I was having bash compatibility issues here. Small change

### CODE REVIEW

**Comment by pkubatrh** [comment]
Thanks for the PR!

Can you also add the same compatibility changes to `test.sh` and `tag.sh`?

**Comment by jbornemann** [comment]
@pkubatrh sure. Done.

**Comment by praiskup** [comment]
@jbornemann I'm just curious what shell are you using so the `[[ -v VAR ]]` construct is problematic...  Could you sum-up the original issue in commit message please?

**Comment by praiskup** [comment]
Seems like `test` in bash 4.1.2 (RHEL6) doesn't have `-v` option yet.  So are you working on el6 containers? :)  I'm just curious.

**Comment by jbornemann** [comment]
Yeah, [[ -v ]] is available after bash 4.2. I'm actually using a recent version of Darwin, which includes ancient bash 3.2.

**Comment by praiskup** [comment]
Thanks!

**Pull request closed without merging**
