### PR TITLE
Do not delete secrets with parametr --all

### PR DESCRIPTION
**Pull request by phracek**
This pull request disables deleting all  'secrets' and 'services' over all namespaces. Secrets are used for communication with kubernetes, docker etc.

### CODE REVIEW

**Comment by phracek** [comment]
[test]

**Comment by phracek** [comment]
[test]

**Comment by zmiklank** [comment]
> More detail description. Also part of commit message.

Thank you! Could you please also explain me why the services ("svc") are not deleted?

**Comment by phracek** [comment]
> > More detail description. Also part of commit message.
> 
> Thank you! Could you please also explain me why the services ("svc") are not deleted?

It looks like I did not review it carefully. Services has to be deleted.

**Review by zmiklank — APPROVED** [review]

**Comment by phracek** [comment]
[test]

**Pull request merged**
